//
//  DDCollectionViewChainModel.m
//  DDChainFlex
//
//  Created by Void on 2018/7/3.
//  Copyright © 2018年 afei. All rights reserved.
//

#import "DDCollectionViewChainModel.h"

#define     DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(methodName, DDParamType)      DDFLEX_CHAIN_IMPLEMENTATION(methodName, DDParamType, DDCollectionViewChainModel *, UICollectionView)
@implementation DDCollectionViewChainModel

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(delegate, id<UICollectionViewDelegate>);
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(dataSource, id<UICollectionViewDataSource>);
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(collectionViewLayout, UICollectionViewLayout *);

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(allowsSelection, BOOL);
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(allowsMultipleSelection, BOOL);

#pragma mark - UIScrollView

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(contentSize, CGSize)
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(contentOffset, CGPoint)
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(contentInset, UIEdgeInsets)

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(bounces, BOOL)
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(alwaysBounceVertical, BOOL)
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(alwaysBounceHorizontal, BOOL)

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(pagingEnabled, BOOL)
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(scrollEnabled, BOOL)

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(showsHorizontalScrollIndicator, BOOL)
DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(showsVerticalScrollIndicator, BOOL)

DDFLEX_CHAIN_COLLECTIONVIEW_IMPLEMENTATION(scrollsToTop, BOOL)
@end

DDFLEX_EX_IMPLEMENTATION(UICollectionView, DDCollectionViewChainModel)
