//
//  DDTableViewChainModel.m
//  DDChainFlex
//
//  Created by Void on 2018/7/3.
//  Copyright © 2018年 afei. All rights reserved.
//

#import "DDTableViewChainModel.h"

#define     DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(methodName, DDParamType)      DDFLEX_CHAIN_IMPLEMENTATION(methodName, DDParamType, DDTableViewChainModel *, UITableView)

@implementation DDTableViewChainModel

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(delegate, id<UITableViewDelegate>)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(dataSource, id<UITableViewDataSource>)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(rowHeight, CGFloat)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(sectionHeaderHeight, CGFloat)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(sectionFooterHeight, CGFloat)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(estimatedRowHeight, CGFloat)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(estimatedSectionHeaderHeight, CGFloat)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(estimatedSectionFooterHeight, CGFloat)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(separatorInset, UIEdgeInsets)


DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(editing, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(allowsSelection, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(allowsMultipleSelection, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(allowsSelectionDuringEditing, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(allowsMultipleSelectionDuringEditing, BOOL)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(separatorStyle, UITableViewCellSeparatorStyle)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(separatorColor, UIColor *)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(tableHeaderView, UIView *)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(tableFooterView, UIView *)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(sectionIndexBackgroundColor, UIColor *)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(sectionIndexColor, UIColor *)

#pragma mark - UIScrollView
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(contentSize, CGSize)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(contentOffset, CGPoint)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(contentInset, UIEdgeInsets)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(bounces, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(alwaysBounceVertical, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(alwaysBounceHorizontal, BOOL)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(pagingEnabled, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(scrollEnabled, BOOL)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(showsHorizontalScrollIndicator, BOOL)
DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(showsVerticalScrollIndicator, BOOL)

DDFLEX_CHAIN_TABLEVIEW_IMPLEMENTATION(scrollsToTop, BOOL)

@end

DDFLEX_EX_IMPLEMENTATION(UITableView, DDTableViewChainModel)
