//
//  DDTextViewChainModel.m
//  DDChainFlex
//
//  Created by Void on 2018/7/3.
//  Copyright © 2018年 afei. All rights reserved.
//

#import "DDTextViewChainModel.h"

#define     DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(methodName, DDParamType)      DDFLEX_CHAIN_IMPLEMENTATION(methodName, DDParamType, DDTextViewChainModel *, UITextView)
@implementation DDTextViewChainModel

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(delegate, id<UITextViewDelegate>);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(text, NSString *);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(font, UIFont *);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(textColor, UIColor *);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(textAlignment, NSTextAlignment);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(selectedRange, NSRange);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(editable, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(selectable, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(dataDetectorTypes, UIDataDetectorTypes);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(keyboardType, UIKeyboardType);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(allowsEditingTextAttributes, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(attributedText, NSAttributedString *);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(typingAttributes, NSDictionary *);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(clearsOnInsertion, BOOL);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(textContainerInset, UIEdgeInsets);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(linkTextAttributes, NSDictionary *);

#pragma mark - UIScrollView

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(contentSize, CGSize);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(contentOffset, CGPoint);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(contentInset, UIEdgeInsets);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(bounces, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(alwaysBounceVertical, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(alwaysBounceHorizontal, BOOL);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(pagingEnabled, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(scrollEnabled, BOOL);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(showsHorizontalScrollIndicator, BOOL);
DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(showsVerticalScrollIndicator, BOOL);

DDFLEX_CHAIN_TEXTVIEW_IMPLEMENTATION(scrollsToTop, BOOL)

@end

DDFLEX_EX_IMPLEMENTATION(UITextView, DDTextViewChainModel)
