//
//  DDTextFieldChainModel.m
//  DDChainFlex
//
//  Created by Void on 2018/7/3.
//  Copyright © 2018年 afei. All rights reserved.
//

#import "DDTextFieldChainModel.h"

#define     DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(methodName, DDParamType)      DDFLEX_CHAIN_IMPLEMENTATION(methodName, DDParamType, DDTextFieldChainModel *, UITextField)
@implementation DDTextFieldChainModel

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(text, NSString *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(attributedText, NSAttributedString *);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(font, UIFont *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(textColor, UIColor *);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(textAlignment, NSTextAlignment);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(borderStyle, UITextBorderStyle);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(defaultTextAttributes, NSDictionary *);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(placeholder, NSString *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(attributedPlaceholder, NSAttributedString *)

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(keyboardType, UIKeyboardType);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(clearsOnBeginEditing, BOOL);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(adjustsFontSizeToFitWidth, BOOL);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(minimumFontSize, CGFloat);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(delegate, id<UITextFieldDelegate>);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(background, UIImage *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(disabledBackground, UIImage *);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(allowsEditingTextAttributes, BOOL);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(typingAttributes, NSDictionary *);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(clearButtonMode, UITextFieldViewMode);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(leftView, UIView *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(leftViewMode, UITextFieldViewMode);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(rightView, UIView *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(rightViewMode, UITextFieldViewMode);

DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(inputView, UIView *);
DDFLEX_CHAIN_TEXTFIELD_IMPLEMENTATION(inputAccessoryView, UIView *);

@end

DDFLEX_EX_IMPLEMENTATION(UITextField, DDTextFieldChainModel)
